### ISSUE TITLE
Add `Group` class

### ISSUE THREAD

**Issue by tysonzero** [blamario/monoid-subclasses#22]
`Group` would be a subclass of `LeftCancellative` and `RightCancellative` but not `Cancellative` itself since `Group` is not required to be commutative. `Abelian` would be a subclass of `Cancellative` and `Group`. `LeftGroup` and `RightGroup` could also work as superclasses. 

One thing that this brings up is that maybe a non-commutative variant of the neutral classes is worthwhile, as any non-commutative group is still going to be a non-commutative cancellative.

**Comment by blamario** [comment]
Not having the `Group` class is a part of the library's charter. The package documentation states at the very beginning:

> The package defines several classes that are richer than monoids but less demanding than groups

I may release a new version that relaxes these bounds in the opposite direction, building on semigroups rather than monoids, but I'm not interested in covering groups and richer structures. There are other existing libraries for that.

**Comment by tysonzero** [comment]
I can understand that approach. I guess I just hope in that case that libraries focusing on richer structures decide to depend on this library so that we have a nice hierarchy of classes from bottom to top.
