### ISSUE TITLE
Remove conditional laws

### ISSUE THREAD

**Issue by tysonzero** [blamario/monoid-subclasses#26]
I personally am against "conditional laws", which is laws of the form "if T is also an instance of C, then ...", as they are useless for types that don't implement C, so you can't really build any intuition about the functions in question in the general case. They also give rise to the possibility of a new instance invalidating a previously valid different instance of a seemingly unrelated (not sub or super) typeclass.

The main one I am aware of is:

```
If a GCDMonoid happens to also be a CancellativeMonoid, it should additionally satisfy the following laws:
```

But any others I would also be in favor of removing. Perhaps the above could be replaced with a class that is a subclass of GCD and Cancellative and asserts the above.

**Comment by blamario** [comment]
Thing is, in many cases the law *could* be restated, but explaining it through a reference to a different class is just the simplest solution. Take the newly proposed law for `stripPrefixOverlap`:

    b `isSuffixOf` (a <> stripPrefixOverlap a b)

You don't like that the law relies `isSuffix` from a different class, and neither do I. Easy to fix:

    (∃ x) x <> b == a <> stripPrefixOverlap a b

There, there is no reference to `isSuffixOf` any more, instead we rely on `==` and existential quantifier. Technically, yes, the equality is still a method of a different class but it has a long tradition of abuse. But a more fundamental problem is, this restatement of the law is only a more complicated way to state the (intuitively) same property. Haskell typeclass laws are not machine-checkable, they are written for humans to read.

**Comment by tysonzero** [comment]
For the `GCDMonoid` + `CancellativeMonoid` example I still maintain my original point about new instances invalidating previous ones + the law not actually being universal / practical to rely on. As the discussion of human readable laws doesn't really apply.

I would also say Haskell laws can be somewhat machine checkable, and it is not uncommon for libraries to export `lawFooBarBaz :: Class a => a -> a -> Bool` that you can throw into quickcheck and make sure you always get back `True`.

For the `Monus` case I can see more where you are coming from. Unless there are non-contrived examples of types that are a reasonable `LeftMonus` but not a reasonable `RightReductive`, I would say it would probably be better to just require both `Left` AND `Right` `Reductive` as a superclass to (`Left`|`Right`)`Monus`.

**Comment by blamario** [comment]
After quite a bit of thinking, and trying to construct a counterexample, I've come most of the way to your position. However, if the `(Left|Right)Monus` classes are going to require both the `(Left|Right)Reductive` superclasses, I don't see much point as keeping the former as separate classes. It appears simpler to just collapse both classes' methods into `OverlappingGCDMonoid`. Would you object to this solution?

**Comment by tysonzero** [comment]
I think having a commutative vs non-commutative variant distinction is useful, as some types only form non-commutative monus (`[a]`). However separating left vs right I'm less sure on.

**Comment by blamario** [comment]
I've combined the three classes into one with 599731a.

**Comment by jonathanknowles** [comment]
Hi @tysonzero @blamario 

After merging https://github.com/blamario/monoid-subclasses/pull/48, I'm wondering if you both consider this issue to be fixed?

The example mentioned above was:
> "If a `GCDMonoid` happens to also be a `CancellativeMonoid`, it should additionally satisfy the following laws:"

That particular example was fixed by https://github.com/blamario/monoid-subclasses/pull/48, since the additional laws (which relate to distributivity) now only apply to the [`DistributiveGCDMonoid`](https://github.com/blamario/monoid-subclasses/blob/bf9e41c29bbd962170cecdb832c2e3cd7abd5f67/src/Data/Monoid/GCD.hs#L604) class (and its left and right superclasses), and no longer apply to the more general [`GCDMonoid`](https://github.com/blamario/monoid-subclasses/blob/bf9e41c29bbd962170cecdb832c2e3cd7abd5f67/src/Data/Monoid/GCD.hs#L145) class.

I did have a look through the library for other examples, but couldn't find anything that really stood out, except perhaps for the [`Factorial`](https://hackage.haskell.org/package/monoid-subclasses-1.2.2/docs/Data-Semigroup-Factorial.html#t:Factorial) class, whose [`primePrefix`](https://hackage.haskell.org/package/monoid-subclasses-1.2.2/docs/Data-Semigroup-Factorial.html#v:primePrefix) and [`primeSuffix`](https://hackage.haskell.org/package/monoid-subclasses-1.2.2/docs/Data-Semigroup-Factorial.html#v:primeSuffix) methods both have laws that only apply for types that are also instances of `Monoid`:

> `primePrefix mempty == mempty` for monoids.
> `primeSuffix mempty == mempty` for monoids.

But I'm guessing that those laws could (in principle) be stated as part of the [`FactorialMonoid`](https://hackage.haskell.org/package/monoid-subclasses-1.2.2/docs/Data-Monoid-Factorial.html#t:FactorialMonoid) class.

But perhaps I've missed another example?

**Comment by blamario** [comment]
I can't find any other example either.

**Comment by blamario** [comment]
>    `primePrefix mempty == mempty` for monoids.
>    `primeSuffix mempty == mempty` for monoids.

I considered moving these bits of documentation into `FactorialMonoid` but in fact they're already [stated there](https://github.com/blamario/monoid-subclasses/blob/442ce1078a7a3f96948b2ca63cb913e10db9feff/src/Data/Monoid/Factorial.hs#L55) as laws. I could just remove them but they seem a pretty useful *clarification* of the two methods' behaviour, right where they are. They're not stated as *laws*.

I'm closing the issue then.
