### ISSUE TITLE
CancellativeMonoid vs Group

### ISSUE THREAD

**Issue by beojan** [blamario/monoid-subclasses#8]
The README states that
> Every group (<em>i.e.</em>, every `Monoid a` with the operation `inverse :: a -> a`) is a `CancellativeMonoid` where `a </> b = Just (a <> inverse b)` but not every `CancellativeMonoid` is a group.

However, couldn't every CancellativeMonoid be a Group, with `inverse a = mempty </> a`? Meanwhile, not every group is a CancellativeMonoid if ReductiveMonoids (and hence CancellativeMonoids) are required to be Abelian.

**Comment by blamario** [comment]
Your definition `inverse a = mempty </> a` has a wrong type `s -> Maybe a` instead of the required `a -> a`.

Another way of looking at it is that the only time `mempty </> a` doesn't return `Nothing` is if `a == mempty`, but a proper `inverse` has to return `Just` for every possible value of its argument - which is why its type is `a -> a` instead of `a -> Maybe a`.

Your other point is correct, I should add the word Abelian to that sentence.

**Comment by beojan** [comment]
Isn't CancellativeMonoid defined as being the subclass of
ReductiveMonoid(?) where `a <\> b` always returns Just?

Sincerely,
Beojan Stanislaus

**Comment by beojan** [comment]
I see that in fact `a </> b` can be Nothing if a cannot be written as `x <> y`.

**Comment by blamario** [comment]
More precisely, a </> b == Nothing if a cannot be written as x <> b. This is true for CancellativeMonoid as well as ReductiveMonoid, the difference is that CancellativeMonoid guarantees

    (a <> b) </> b == Just a

for all a and b. For this to be possible, the partial function `(<> b)` cannot lose any information about `a` (i.e., it must be injective). This is why addition is cancellative while multiplication is merely reductive.
